danceparty/danceparty/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dancepartyapp import views as dancepartyviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('dancepartyapp.urls', namespace='danceparty')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

danceparty/dancepartyapp/urls.py
from django.urls import path

from dancepartyapp import views

app_name = 'dancepartyapp'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('join_dance_party/<int:pk>/', views.join_dance_party, name='join_dance_party'),
    path('leave_dance_party/<int:pk>/', views.leave_dance_party, name='leave_dance_party'),
]

danceparty/dancepartyapp/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models

"""
Table 1​ should include columns- 
Location of dance party (link to dance party page), 
party start datetime, 
party end time, 
the theme of party, 
leave party link. 
When the logged in user creates a dance party they should automatically be “joined” to that party and 
it should be listed here.
"""


class DanceParty(models.Model):
    PARTY_THEMES = (
        ('BIRTHDAY_PARTY', 'BIRTHDAY_PARTY'),
        ('TEA_PARTY', 'TEA_PARTY'),
        ('WEDDING_PARTY', 'WEDDING_PARTY'),
        ('OTHER', 'OTHER')
    )

    page_link = models.CharField(max_length=100)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    theme = models.CharField(max_length=50, choices=PARTY_THEMES, default='OTHER')
    participants = models.ManyToManyField(User)

    def __str__(self):
        return 'page link - {}, theme - {}'.format(self.page_link, self.theme)

danceparty/dancepartyapp/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template import loader

from dancepartyapp.models import DanceParty


@login_required
def dashboard(request):
    logged_user = request.user
    joined_dance_parties = DanceParty.objects.filter(participants=logged_user)
    unjoined_dance_parties = DanceParty.objects.filter(~Q(participants=logged_user))
    template = loader.get_template('dashboard.html')
    context = {
        'joined_dance_parties': joined_dance_parties,
        'unjoined_dance_parties': unjoined_dance_parties
    }
    return HttpResponse(template.render(context, request))


@login_required
def join_dance_party(request, pk):
    logged_user = request.user
    dance_party = DanceParty.objects.get(pk=pk)
    dance_party.participants.add(logged_user)
    return redirect('dancepartyapp:dashboard')


@login_required
def leave_dance_party(request, pk):
    logged_user = request.user
    dance_party = DanceParty.objects.get(pk=pk)
    dance_party.participants.remove(logged_user)
    return redirect('dancepartyapp:dashboard')

danceparty/dancepartyapp/templates/dashboard.html
{% load staticfiles %}
<html>
<head>
    <title>Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>

<body>
<div class="container">
    <h1>Dashboard</h1>

    <h3>Currently joined parties</h3>

    <table class="table table-striped table-bordered">
        <thead>
        <th>Id</th>
        <th>Link</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Theme</th>
        <th>Action</th>
        </thead>

        <tbody>
        {% for party in joined_dance_parties %}
            <tr>
                <td>{{ party.id }}</td>
                <td>
                    <a href="#">{{ party.page_link }}</a>
                </td>
                <td>{{ party.start_time }}</td>
                <td>{{ party.end_time }}</td>
                <td>{{ party.theme }}</td>
                <td>
                    <a class="btn btn-secondary" href="{% url 'dancepartyapp:leave_dance_party' party.id %}">Leave</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <h3>Parties not participated in:</h3>

    <table class="table table-striped table-bordered">
        <thead>
        <th>Id</th>
        <th>Link</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Theme</th>
        <th>Action</th>
        </thead>

        <tbody>
        {% for party in unjoined_dance_parties %}
            <tr>
                <td>{{ party.id }}</td>
                <td>
                    <a href="#">{{ party.page_link }}</a>
                </td>
                <td>{{ party.start_time }}</td>
                <td>{{ party.end_time }}</td>
                <td>{{ party.theme }}</td>
                <td>
                    <a class="btn btn-secondary" href="{% url 'dancepartyapp:join_dance_party' party.id %}">Join</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>

</html>